### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by telkins** [bakame-php/dice-roller#3]
## Issue summary

The docs have pretty straightforward instructions on how to install:
```
$ composer require bakame-php/dice-roller
```

### System informations

I'm not sure what to put here.  Please let me know if there's any additional information that might help.

## Standalone code, or other way to reproduce the problem

I go to the command line and execute the following command:
```
$ composer require bakame-php/dice-roller
```

### Expected result
The package is installed.

### Actual result
The package is not installed and the following message is displayed:
```
Could not find a matching version of package bakame-php/dice-roller. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (dev).
```

I also noticed that the readme.md doc shows the following on the package's main github page:
```
release | no releases or repo not found
```

Also, I can't find the package on packagist.org....but perhaps I'm looking in the wrong place...?

**Comment by nyamsprod** [comment]
@telkins yes currently the code is not yet on packagist 👍 the reason being that I'm not really ready to do it yet

**Comment by telkins** [comment]
@nyamsprod OK.  Thx for the info.  I guess I'd like to know, then, how you might suggest we install it.  :-)

**Comment by telkins** [comment]
@nyamsprod Any updates on this?

**Comment by nyamsprod** [comment]
I'd say the easiest way for you would be to fork and release it's MIT so it's okay 😉. Also this package is already a fork from a previous one so I really have no objections in you doing the same here 👍

**Comment by telkins** [comment]
@nyamsprod Thx.  Sounds good.  Appreciate the response.  :-)

**Comment by deurk** [comment]
@nyamsprod Could you please detail the best way to install the dice-roller and its dependencies ? I've tried adding this github as a composer repository and succeeded make dice-roller a dependency but then my php script fails on the uses (```Uncaught Error: Class 'Bakame\DiceRoller\ExpressionParser' not found```).

**Comment by deurk** [comment]
OK, I've defined it in the my app `composer.json` this way :
```
{
  "require": {
    "php": "^7.2",
    "psr/log": "^1.1"
  },
  "autoload": {
    "psr-4": {
      "Bakame\\DiceRoller\\": "./dice-roller/src"
    }
  }
}
```
and `git clone`d this repo to get the files. Now it works properly.

**Comment by deurk** [comment]
Also had to add the line `require_once __DIR__ . '/vendor/autoload.php';` to my app before the `use` declarations.

**Comment by nyamsprod** [comment]
This package will stay unpublished for the forseeing future the best anyone can do if he/she wishes to use it is to fork it and make it his/her own.
