### ISSUE TITLE
Feature request : Count dice rolled over X or under Y

### ISSUE THREAD

**Issue by deurk** [bakame-php/dice-roller#4]
Would it be possible to have the same syntax as the exploding conditions (<3, >5 etc) but instead of exploding the dice, just return the count of matching dice ?

/roll 4d6>3 would return { 3, 5, 1, 4 } and count = 2.

Thanks :)

**Comment by nyamsprod** [comment]
@deurk if you follow the `Bakame\DiceRoller\Contract\Modifier` nothing should prevent you from adding such modifier 😉

**Comment by nyamsprod** [comment]
@deurk maybe this can be also inferred from the last trace 🤔🤔 or added in the profiler 🤔🤔

**Comment by nyamsprod** [comment]
@deurk the package has been updated and the tracing has been re-written from scratch ... bottom line with the new tracing capability and the the `Roll` object what you want could be easily achieved without some simple logic.

And yes this package will **NEVER** be stable 😈 

A better strategy is to fork it and release it for yourself 😉
